name: e2e test with cypress

on:
  push:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cypress:headless
